apiVersion: 1

datasources:
  - name: InfluxDB ESP32-S3 Bandwidth
    uid: influxdb_bandwidth
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: neural-link-lab
      defaultBucket: esp32s3_bandwidth
      tlsSkipVerify: true
    secureJsonData:
      token: bandwidth-monitor-token
